// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: proto/controlplane.proto

package controlplane

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_RegisterBreakpoint_FullMethodName = "/controlplane.ControlPlane/RegisterBreakpoint"
	ControlPlane_ListBreakpoints_FullMethodName    = "/controlplane.ControlPlane/ListBreakpoints"
	ControlPlane_DeleteBreakPoint_FullMethodName   = "/controlplane.ControlPlane/DeleteBreakPoint"
	ControlPlane_GetSnapshot_FullMethodName        = "/controlplane.ControlPlane/GetSnapshot"
	ControlPlane_StreamTraces_FullMethodName       = "/controlplane.ControlPlane/StreamTraces"
	ControlPlane_FreezeTrace_FullMethodName        = "/controlplane.ControlPlane/FreezeTrace"
	ControlPlane_GetFreezeStatus_FullMethodName    = "/controlplane.ControlPlane/GetFreezeStatus"
	ControlPlane_ReleaseTrace_FullMethodName       = "/controlplane.ControlPlane/ReleaseTrace"
	ControlPlane_ListActiveFreezes_FullMethodName  = "/controlplane.ControlPlane/ListActiveFreezes"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneClient interface {
	RegisterBreakpoint(ctx context.Context, in *RegisterBreakPointRequest, opts ...grpc.CallOption) (*RegisterBreakPointResponse, error)
	ListBreakpoints(ctx context.Context, in *ListBreakpointsRequest, opts ...grpc.CallOption) (*ListBreakpointsResponse, error)
	DeleteBreakPoint(ctx context.Context, in *DeleteBreakPointRequest, opts ...grpc.CallOption) (*DeleteBreakPointResponse, error)
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	StreamTraces(ctx context.Context, in *StreamTracesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TraceEvent], error)
	FreezeTrace(ctx context.Context, in *FreezeTraceRequest, opts ...grpc.CallOption) (*FreezeTraceResponse, error)
	GetFreezeStatus(ctx context.Context, in *GetFreezeStatusRequest, opts ...grpc.CallOption) (*GetFreezeStatusResponse, error)
	ReleaseTrace(ctx context.Context, in *ReleaseTraceRequest, opts ...grpc.CallOption) (*ReleaseTraceResponse, error)
	ListActiveFreezes(ctx context.Context, in *ListActiveFreezesRequest, opts ...grpc.CallOption) (*ListActiveFreezesResponse, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) RegisterBreakpoint(ctx context.Context, in *RegisterBreakPointRequest, opts ...grpc.CallOption) (*RegisterBreakPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterBreakPointResponse)
	err := c.cc.Invoke(ctx, ControlPlane_RegisterBreakpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListBreakpoints(ctx context.Context, in *ListBreakpointsRequest, opts ...grpc.CallOption) (*ListBreakpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBreakpointsResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ListBreakpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) DeleteBreakPoint(ctx context.Context, in *DeleteBreakPointRequest, opts ...grpc.CallOption) (*DeleteBreakPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBreakPointResponse)
	err := c.cc.Invoke(ctx, ControlPlane_DeleteBreakPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, ControlPlane_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) StreamTraces(ctx context.Context, in *StreamTracesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TraceEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlane_ServiceDesc.Streams[0], ControlPlane_StreamTraces_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTracesRequest, TraceEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamTracesClient = grpc.ServerStreamingClient[TraceEvent]

func (c *controlPlaneClient) FreezeTrace(ctx context.Context, in *FreezeTraceRequest, opts ...grpc.CallOption) (*FreezeTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreezeTraceResponse)
	err := c.cc.Invoke(ctx, ControlPlane_FreezeTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) GetFreezeStatus(ctx context.Context, in *GetFreezeStatusRequest, opts ...grpc.CallOption) (*GetFreezeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFreezeStatusResponse)
	err := c.cc.Invoke(ctx, ControlPlane_GetFreezeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ReleaseTrace(ctx context.Context, in *ReleaseTraceRequest, opts ...grpc.CallOption) (*ReleaseTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseTraceResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ReleaseTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ListActiveFreezes(ctx context.Context, in *ListActiveFreezesRequest, opts ...grpc.CallOption) (*ListActiveFreezesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveFreezesResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ListActiveFreezes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
type ControlPlaneServer interface {
	RegisterBreakpoint(context.Context, *RegisterBreakPointRequest) (*RegisterBreakPointResponse, error)
	ListBreakpoints(context.Context, *ListBreakpointsRequest) (*ListBreakpointsResponse, error)
	DeleteBreakPoint(context.Context, *DeleteBreakPointRequest) (*DeleteBreakPointResponse, error)
	GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	StreamTraces(*StreamTracesRequest, grpc.ServerStreamingServer[TraceEvent]) error
	FreezeTrace(context.Context, *FreezeTraceRequest) (*FreezeTraceResponse, error)
	GetFreezeStatus(context.Context, *GetFreezeStatusRequest) (*GetFreezeStatusResponse, error)
	ReleaseTrace(context.Context, *ReleaseTraceRequest) (*ReleaseTraceResponse, error)
	ListActiveFreezes(context.Context, *ListActiveFreezesRequest) (*ListActiveFreezesResponse, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) RegisterBreakpoint(context.Context, *RegisterBreakPointRequest) (*RegisterBreakPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterBreakpoint not implemented")
}
func (UnimplementedControlPlaneServer) ListBreakpoints(context.Context, *ListBreakpointsRequest) (*ListBreakpointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBreakpoints not implemented")
}
func (UnimplementedControlPlaneServer) DeleteBreakPoint(context.Context, *DeleteBreakPointRequest) (*DeleteBreakPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBreakPoint not implemented")
}
func (UnimplementedControlPlaneServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedControlPlaneServer) StreamTraces(*StreamTracesRequest, grpc.ServerStreamingServer[TraceEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTraces not implemented")
}
func (UnimplementedControlPlaneServer) FreezeTrace(context.Context, *FreezeTraceRequest) (*FreezeTraceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FreezeTrace not implemented")
}
func (UnimplementedControlPlaneServer) GetFreezeStatus(context.Context, *GetFreezeStatusRequest) (*GetFreezeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFreezeStatus not implemented")
}
func (UnimplementedControlPlaneServer) ReleaseTrace(context.Context, *ReleaseTraceRequest) (*ReleaseTraceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseTrace not implemented")
}
func (UnimplementedControlPlaneServer) ListActiveFreezes(context.Context, *ListActiveFreezesRequest) (*ListActiveFreezesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActiveFreezes not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call pancis, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_RegisterBreakpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBreakPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).RegisterBreakpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_RegisterBreakpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).RegisterBreakpoint(ctx, req.(*RegisterBreakPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListBreakpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBreakpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListBreakpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListBreakpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListBreakpoints(ctx, req.(*ListBreakpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_DeleteBreakPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBreakPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).DeleteBreakPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_DeleteBreakPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).DeleteBreakPoint(ctx, req.(*DeleteBreakPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_StreamTraces_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTracesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServer).StreamTraces(m, &grpc.GenericServerStream[StreamTracesRequest, TraceEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlane_StreamTracesServer = grpc.ServerStreamingServer[TraceEvent]

func _ControlPlane_FreezeTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).FreezeTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_FreezeTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).FreezeTrace(ctx, req.(*FreezeTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_GetFreezeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFreezeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).GetFreezeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_GetFreezeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).GetFreezeStatus(ctx, req.(*GetFreezeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ReleaseTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ReleaseTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ReleaseTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ReleaseTrace(ctx, req.(*ReleaseTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ListActiveFreezes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveFreezesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ListActiveFreezes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ListActiveFreezes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ListActiveFreezes(ctx, req.(*ListActiveFreezesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controlplane.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterBreakpoint",
			Handler:    _ControlPlane_RegisterBreakpoint_Handler,
		},
		{
			MethodName: "ListBreakpoints",
			Handler:    _ControlPlane_ListBreakpoints_Handler,
		},
		{
			MethodName: "DeleteBreakPoint",
			Handler:    _ControlPlane_DeleteBreakPoint_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _ControlPlane_GetSnapshot_Handler,
		},
		{
			MethodName: "FreezeTrace",
			Handler:    _ControlPlane_FreezeTrace_Handler,
		},
		{
			MethodName: "GetFreezeStatus",
			Handler:    _ControlPlane_GetFreezeStatus_Handler,
		},
		{
			MethodName: "ReleaseTrace",
			Handler:    _ControlPlane_ReleaseTrace_Handler,
		},
		{
			MethodName: "ListActiveFreezes",
			Handler:    _ControlPlane_ListActiveFreezes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTraces",
			Handler:       _ControlPlane_StreamTraces_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/controlplane.proto",
}
